export const WEB_URL = {
  guestHome: "/guest",
  login: "/login",
  loginCallback: "/login/callback",
  guestTarot: "/draw/guest",

  home: "/",
  tarot: "/draw",
  aiTarot: "/draw/ai",
  aiTarotResult: "/result/ai",
  aiDeepTarotTwelveHouses: "/draw/deep/twelve-houses",
  aiDeepTarotTwelveMonths: "/draw/deep/twelve-months",
  aiDeepTarotCrossroads: "/draw/deep/crossroads",
  aiDeepTarotResult: "/result/deep",
  tarotHistory: "/history",
  aiTarotHistory: "/history/ai",
  aiDeepTarotHistory: "/history/deep",
  library: "/library",
  wallet: "/wallet",
} as const;
