using MyTarotReader.Domain.Enums;

namespace MyTarotReader.Application.Contracts.Services;

/// <summary>
/// A single drawn card sent from the frontend when creating a deep tarot reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiDeepCardRequest(string CardCode, bool IsReversed);

/// <summary>
/// Request to create a deep tarot reading.
/// </summary>
/// <param name="Topic">The specialized topic of the reading.</param>
/// <param name="Locale">The response language of the reading ("en" or "vi").</param>
/// <param name="Cards">The drawn cards, whose count must match the topic's spread size.</param>
public record CreateAiDeepTarotReadingRequest(
    DeepTarotTopic Topic,
    string Locale,
    List<AiDeepCardRequest> Cards
);

/// <summary>
/// A drawn tarot card of an existing deep reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiDeepReadingCard(string CardCode, bool IsReversed);

/// <summary>
/// Result of creating a deep tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
public record CreateAiDeepTarotReadingResult(Guid Id);

/// <summary>
/// Result of retrieving a single deep tarot reading.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="Topic">The specialized topic of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="Answer">The full structured answer generated by the AI.</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
public record GetAiDeepTarotReadingResult(
    Guid Id,
    DeepTarotTopic Topic,
    string Title,
    string Answer,
    List<AiDeepReadingCard> Cards,
    DateTimeOffset CreatedAt
);

/// <summary>
/// A single deep tarot reading entry in the user's reading history.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="Topic">The specialized topic of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="AnswerSummary">A short excerpt of the answer (not the full answer).</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
public record GetAllAiDeepTarotReadingItem(
    Guid Id,
    DeepTarotTopic Topic,
    string Title,
    string AnswerSummary,
    List<AiDeepReadingCard> Cards,
    DateTimeOffset CreatedAt
);

/// <summary>
/// Result of retrieving all deep tarot readings for a user.
/// </summary>
/// <param name="Items">The list of readings.</param>
public record GetAllAiDeepTarotReadingResult(List<GetAllAiDeepTarotReadingItem> Items);

public interface IAIDeepTarotReadingService
{
    /// <summary>
    /// Creates a new deep tarot reading by generating the answer with Gemini and persisting it.
    /// </summary>
    /// <param name="request"><see cref="CreateAiDeepTarotReadingRequest"/> containing the topic, locale and drawn cards.</param>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="CreateAiDeepTarotReadingResult"/> with the ID of the created reading.</returns>
    /// <exception cref="BadRequestException">Thrown when the request validation fails.</exception>
    /// <exception cref="InternalServerException">Thrown when the Gemini API call fails.</exception>
    Task<CreateAiDeepTarotReadingResult> CreateAiDeepTarotReadingAsync(
        CreateAiDeepTarotReadingRequest request,
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves a single deep tarot reading for the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to retrieve.</param>
    /// <returns><see cref="GetAiDeepTarotReadingResult"/> containing the full reading.</returns>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task<GetAiDeepTarotReadingResult> GetAiDeepTarotReadingByIdAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves all deep tarot readings for the user, without the full answer.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="GetAllAiDeepTarotReadingResult"/> containing a short excerpt per reading.</returns>
    Task<GetAllAiDeepTarotReadingResult> GetAllAiDeepTarotReadingsAsync(
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Soft-deletes a deep tarot reading owned by the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to delete.</param>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task DeleteAiDeepTarotReadingAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );
}
