using MyTarotReader.Domain.Enums;

namespace MyTarotReader.Application.Contracts.Services;

/// <summary>
/// A single drawn card sent from the frontend when creating a deep tarot reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiDeepCardRequest(string CardCode, bool IsReversed);

/// <summary>
/// The shape shared by every deep tarot create request: a response language and the drawn cards.
/// </summary>
/// <remarks>
/// Implemented by each spread's own request record so a future spread with a different input
/// (extra fields, a different card list) can declare its own record without changing the
/// spreads that already exist.
/// </remarks>
public interface ICreateDeepTarotReadingRequest
{
    /// <summary>
    /// The response language of the reading ("en" or "vi").
    /// </summary>
    string Locale { get; }

    /// <summary>
    /// The drawn cards of the spread.
    /// </summary>
    List<AiDeepCardRequest> Cards { get; }
}

/// <summary>
/// Request to create a 12 astrological houses deep tarot reading.
/// </summary>
/// <param name="Locale">The response language of the reading ("en" or "vi").</param>
/// <param name="Cards">The drawn cards, one per house.</param>
public record CreateTwelveHousesReadingRequest(
    string Locale,
    List<AiDeepCardRequest> Cards
) : ICreateDeepTarotReadingRequest;

/// <summary>
/// Result of creating a 12 astrological houses deep tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
public record CreateTwelveHousesReadingResult(Guid Id);

/// <summary>
/// Request to create a 12 months deep tarot reading.
/// </summary>
/// <param name="Locale">The response language of the reading ("en" or "vi").</param>
/// <param name="Cards">The drawn cards, one per month. The spread runs from the month after
/// the month the reading is created in.</param>
public record CreateTwelveMonthsReadingRequest(
    string Locale,
    List<AiDeepCardRequest> Cards
) : ICreateDeepTarotReadingRequest;

/// <summary>
/// Result of creating a 12 months deep tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
public record CreateTwelveMonthsReadingResult(Guid Id);

/// <summary>
/// Request to create a crossroads (decision between options) deep tarot reading.
/// </summary>
/// <param name="Locale">The response language of the reading ("en" or "vi").</param>
/// <param name="Question">The decision the user is facing, in their own words.</param>
/// <param name="Options">The options being compared, between 2 and 4 of them.</param>
/// <param name="TimeFrame">The horizon over which the decision is evaluated, optional.</param>
/// <param name="Cards">The drawn cards: three per option, plus one closing summary card.</param>
public record CreateCrossroadsReadingRequest(
    string Locale,
    string Question,
    List<string> Options,
    CrossroadsTimeFrame? TimeFrame,
    List<AiDeepCardRequest> Cards
) : ICreateDeepTarotReadingRequest;

/// <summary>
/// Result of creating a crossroads deep tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
public record CreateCrossroadsReadingResult(Guid Id);

/// <summary>
/// A drawn tarot card of an existing deep reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiDeepReadingCard(string CardCode, bool IsReversed);

/// <summary>
/// Result of creating a deep tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
/// <summary>
/// Result of retrieving a single deep tarot reading.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="Topic">The specialized topic of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="Answer">The full structured answer generated by the AI.</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
/// <param name="Question">The question the user asked, only set by spreads that accept free text.</param>
/// <param name="Options">The options compared, only set by the crossroads spread.</param>
/// <param name="TimeFrame">The decision horizon, only set by the crossroads spread.</param>
public record GetAiDeepTarotReadingResult(
    Guid Id,
    DeepTarotTopic Topic,
    string Title,
    string Answer,
    List<AiDeepReadingCard> Cards,
    DateTimeOffset CreatedAt,
    string? Question = null,
    List<string>? Options = null,
    CrossroadsTimeFrame? TimeFrame = null
);

/// <summary>
/// A single deep tarot reading entry in the user's reading history.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="Topic">The specialized topic of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="AnswerSummary">A short excerpt of the answer (not the full answer).</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
/// <param name="Question">The question the user asked, only set by spreads that accept free text.</param>
public record GetAllAiDeepTarotReadingItem(
    Guid Id,
    DeepTarotTopic Topic,
    string Title,
    string AnswerSummary,
    List<AiDeepReadingCard> Cards,
    DateTimeOffset CreatedAt,
    string? Question = null
);

/// <summary>
/// Request for retrieving a page of deep tarot readings for a user.
/// </summary>
/// <param name="Page">The 1-based page number.</param>
/// <param name="PageSize">The number of items per page.</param>
public record GetAllAiDeepTarotReadingRequest(int Page = 1, int PageSize = 10);

/// <summary>
/// Result of retrieving a page of deep tarot readings for a user.
/// </summary>
/// <param name="Items">The readings of the requested page.</param>
/// <param name="Page">The normalized 1-based page number.</param>
/// <param name="PageSize">The normalized number of items per page.</param>
/// <param name="Total">The total number of readings across all pages.</param>
/// <param name="TotalPages">The total number of pages.</param>
public record GetAllAiDeepTarotReadingResult(
    List<GetAllAiDeepTarotReadingItem> Items,
    int Page,
    int PageSize,
    int Total,
    int TotalPages
);

public interface IAIDeepTarotReadingService
{
    /// <summary>
    /// Creates a new 12 astrological houses reading by generating the answer with Gemini
    /// and persisting it.
    /// </summary>
    /// <param name="request"><see cref="CreateTwelveHousesReadingRequest"/> containing the locale and the 12 drawn cards.</param>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="CreateTwelveHousesReadingResult"/> with the ID of the created reading.</returns>
    /// <exception cref="BadRequestException">Thrown when the request validation fails or the user does not have enough red coins.</exception>
    /// <exception cref="InternalServerException">Thrown when the Gemini API call fails.</exception>
    /// <remarks>The topic's red coin cost is charged only after the answer has been generated.</remarks>
    Task<CreateTwelveHousesReadingResult> CreateTwelveHousesReadingAsync(
        CreateTwelveHousesReadingRequest request,
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Creates a new 12 months reading by generating the answer with Gemini and persisting it.
    /// </summary>
    /// <param name="request"><see cref="CreateTwelveMonthsReadingRequest"/> containing the locale and the 12 drawn cards.</param>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="CreateTwelveMonthsReadingResult"/> with the ID of the created reading.</returns>
    /// <exception cref="BadRequestException">Thrown when the request validation fails or the user does not have enough red coins.</exception>
    /// <exception cref="InternalServerException">Thrown when the Gemini API call fails.</exception>
    /// <remarks>
    /// The 12 positions cover the consecutive calendar months starting the month after the
    /// reading is created; the red coin cost is charged only after the answer has been generated.
    /// </remarks>
    Task<CreateTwelveMonthsReadingResult> CreateTwelveMonthsReadingAsync(
        CreateTwelveMonthsReadingRequest request,
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Creates a new crossroads reading by generating the answer with Gemini and persisting it.
    /// </summary>
    /// <param name="request"><see cref="CreateCrossroadsReadingRequest"/> containing the question, the options and the drawn cards.</param>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="CreateCrossroadsReadingResult"/> with the ID of the created reading.</returns>
    /// <exception cref="BadRequestException">Thrown when the request validation fails or the user does not have enough red coins.</exception>
    /// <exception cref="InternalServerException">Thrown when the Gemini API call fails.</exception>
    /// <remarks>
    /// The spread holds three cards per option plus one closing summary card, and costs one
    /// red coin per option; both are charged only after the answer has been generated.
    /// </remarks>
    Task<CreateCrossroadsReadingResult> CreateCrossroadsReadingAsync(
        CreateCrossroadsReadingRequest request,
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves a single deep tarot reading for the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to retrieve.</param>
    /// <returns><see cref="GetAiDeepTarotReadingResult"/> containing the full reading.</returns>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task<GetAiDeepTarotReadingResult> GetAiDeepTarotReadingByIdAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves a page of deep tarot readings for the user, without the full answer.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="request"><see cref="GetAllAiDeepTarotReadingRequest"/> containing the page and page size.</param>
    /// <returns><see cref="GetAllAiDeepTarotReadingResult"/> containing one page with a short excerpt per reading.</returns>
    Task<GetAllAiDeepTarotReadingResult> GetAllAiDeepTarotReadingsAsync(
        Guid userId,
        GetAllAiDeepTarotReadingRequest request,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Soft-deletes a deep tarot reading owned by the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to delete.</param>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task DeleteAiDeepTarotReadingAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );
}
