using MyTarotReader.Domain.Enums;

namespace MyTarotReader.Application.Contracts.Services;

/// <summary>
/// A single drawn card sent from the frontend when creating an AI tarot reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiCardRequest(string CardCode, bool IsReversed);

/// <summary>
/// Request to create an AI tarot reading.
/// </summary>
/// <param name="CardCount">The number of cards in the spread.</param>
/// <param name="Type">The question type of the reading.</param>
/// <param name="Locale">The response language of the reading ("en" or "vi").</param>
/// <param name="Cards">The drawn cards, whose count must match <paramref name="CardCount"/>.</param>
public record CreateAiTarotReadingRequest(
    CardCount CardCount,
    QuestionType Type,
    string Locale,
    List<AiCardRequest> Cards
);

/// <summary>
/// A drawn tarot card of an existing AI reading.
/// </summary>
/// <param name="CardCode">The tarot card code.</param>
/// <param name="IsReversed">Indicates if the card is reversed.</param>
public record AiReadingCard(string CardCode, bool IsReversed);

/// <summary>
/// Result of retrieving a single AI tarot reading.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="CardCount">The number of cards in the spread.</param>
/// <param name="Type">The question type of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="Answer">The full structured answer generated by the AI.</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
public record GetAiTarotReadingResult(
    Guid Id,
    CardCount CardCount,
    QuestionType Type,
    string Title,
    string Answer,
    List<AiReadingCard> Cards,
    DateTimeOffset CreatedAt
);

/// <summary>
/// A single AI tarot reading entry in the user's reading history.
/// </summary>
/// <param name="Id">The reading ID.</param>
/// <param name="CardCount">The number of cards in the spread.</param>
/// <param name="Type">The question type of the reading.</param>
/// <param name="Title">The AI-generated title of the reading.</param>
/// <param name="AnswerSummary">A short excerpt of the answer (not the full answer).</param>
/// <param name="Cards">The drawn cards.</param>
/// <param name="CreatedAt">The creation time of the reading.</param>
public record GetAllAiTarotReadingItem(
    Guid Id,
    CardCount CardCount,
    QuestionType Type,
    string Title,
    string AnswerSummary,
    List<AiReadingCard> Cards,
    DateTimeOffset CreatedAt
);

/// <summary>
/// Result of retrieving all AI tarot readings for a user.
/// </summary>
/// <param name="Items">The list of readings.</param>
public record GetAllAiTarotReadingResult(List<GetAllAiTarotReadingItem> Items);

/// <summary>
/// Result of creating an AI tarot reading.
/// </summary>
/// <param name="Id">The ID of the newly created reading.</param>
public record CreateAiTarotReadingResult(Guid Id);

public interface IAiTarotReadingService
{
    /// <summary>
    /// Creates a new AI tarot reading by generating the answer with Gemini and persisting it.
    /// </summary>
    /// <param name="request"><see cref="CreateAiTarotReadingRequest"/> containing the spread configuration and drawn cards.</param>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="CreateAiTarotReadingResult"/> with the ID of the created reading.</returns>
    /// <exception cref="BadRequestException">Thrown when the request validation fails.</exception>
    /// <exception cref="InternalServerException">Thrown when the Gemini API call fails.</exception>
    Task<CreateAiTarotReadingResult> CreateAiTarotReadingAsync(
        CreateAiTarotReadingRequest request,
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves a single AI tarot reading for the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to retrieve.</param>
    /// <returns><see cref="GetAiTarotReadingResult"/> containing the full reading.</returns>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task<GetAiTarotReadingResult> GetAiTarotReadingByIdAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Retrieves all AI tarot readings for the user, without the full answer.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <returns><see cref="GetAllAiTarotReadingResult"/> containing a short excerpt per reading.</returns>
    Task<GetAllAiTarotReadingResult> GetAllAiTarotReadingsAsync(
        Guid userId,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Soft-deletes an AI tarot reading owned by the user.
    /// </summary>
    /// <param name="userId">The authenticated user's ID.</param>
    /// <param name="readingId">The ID of the reading to delete.</param>
    /// <exception cref="NotFoundException">Thrown when the reading does not exist for the user.</exception>
    Task DeleteAiTarotReadingAsync(
        Guid userId,
        Guid readingId,
        CancellationToken cancellationToken = default
    );
}