using MyTarotReader.Domain.Common;
using MyTarotReader.Domain.Enums;

namespace MyTarotReader.Domain.Entities;

/// <summary>
/// A specialized (deep) tarot reading: a fixed, topic-specific spread whose
/// interpretation is generated by AI.
/// </summary>
public class AIDeepTarotReading : BaseEntity
{
    public Guid UserId { get; set; }

    public DeepTarotTopic Topic { get; set; }

    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// A short excerpt of the answer (overview) used for list views,
    /// so callers do not have to fetch the full reading.
    /// </summary>
    public string AnswerSummary { get; set; } = string.Empty;

    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// The cards drawn for the spread, represented as a string.
    /// </summary>
    /// <remarks>
    /// This property stores the cards by JSON serialization.
    /// </remarks>
    public string Cards { get; set; } = string.Empty;

    /// <summary>
    /// The question the user asked, only set by spreads that accept free text.
    /// </summary>
    public string? Question { get; set; }

    /// <summary>
    /// The options the user is choosing between, represented as a string.
    /// </summary>
    /// <remarks>
    /// This property stores the options by JSON serialization and is only set by
    /// <see cref="DeepTarotTopic.Crossroads"/>, whose spread is sized by their count.
    /// </remarks>
    public string? Options { get; set; }

    /// <summary>
    /// The horizon over which the decision is evaluated, only set by
    /// <see cref="DeepTarotTopic.Crossroads"/>.
    /// </summary>
    public CrossroadsTimeFrame? TimeFrame { get; set; }

    #region Navigation Properties
    public User User { get; set; } = null!;

    #endregion
}
